apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: snackshack
data:
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
  JAVA_HOME: /usr/lib/jvm/default-java
